@OpenTriviaDbWebService_HostAddress = http://localhost:5002

# GET categories: Get all available trivia categories with caching
GET {{OpenTriviaDbWebService_HostAddress}}/OpenTriviaDbWebService/get_categories/
Accept: application/json

###

# STEP 1: Get a new quiz and fresh token
POST {{OpenTriviaDbWebService_HostAddress}}/OpenTriviaDbWebService/get_quiz/
Accept: application/json
Content-Type: application/json

{
  "numberOfQuestions": 5,
  "category": 10,
  "quizType": 2,
  "difficulty": 1
}

###

# STEP 2: Use the token from the X-Session-Token response header above
POST {{OpenTriviaDbWebService_HostAddress}}/OpenTriviaDbWebService/check_answers/
Accept: application/json
Content-Type: application/json

{
  "token": "d914d41f-839b-49a3-af31-b75a036b5d7a",
  "question_id": 0,
  "question": "The%20book%201984%20was%20published%20in%201949.",
  "answer": "True"
}